version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Build distribution
          command: mvn -B -s maven-settings.xml install -Pdistribution -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
